version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HCDE"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14udktfoz9o2h"
s3_prefix = "HCDE"
region = "me-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["Getappropriatetest=708411206515.dkr.ecr.me-south-1.amazonaws.com/hcdec66a7f93/getappropriatetest99f2dad1repo"]
disable_rollback = true
